//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buchungssystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Buchung
    {
        public int Id { get; set; }
        public int TischId { get; set; }
        public int WarenId { get; set; }
        public System.DateTime Zeitpunkt { get; set; }
        public int Status { get; set; }
    
        public virtual Tisch Tisch { get; set; }
        public virtual Ware Ware { get; set; }
    }
}
