//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buchungssystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservierung
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public System.DateTime Uhrzeit { get; set; }
        public Nullable<int> TischId { get; set; }
    
        public virtual Tisch Tisch { get; set; }
    }
}
