//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buchungssystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tisch
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tisch()
        {
            this.Buchung = new HashSet<Buchung>();
            this.Reservierung = new HashSet<Reservierung>();
        }
    
        public int Id { get; set; }
        public string Bezeichnung { get; set; }
        public Nullable<int> Platze { get; set; }
        public int RaumId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchung> Buchung { get; set; }
        public virtual Raum Raum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reservierung> Reservierung { get; set; }
    }
}
