//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Buchungssystem.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ware
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ware()
        {
            this.Buchung = new HashSet<Buchung>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public decimal Preis { get; set; }
        public int WarengruppenId { get; set; }
        public bool Deleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Buchung> Buchung { get; set; }
        public virtual Warengruppe Warengruppe { get; set; }
    }
}
