//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stundenplan.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class StundenplanEntities : DbContext
    {
        public StundenplanEntities()
            : base("name=StundenplanEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Studenplan_Stunden> Studenplan_Stunden { get; set; }
        public virtual DbSet<Stundenplan> Stundenplans { get; set; }
        public virtual DbSet<Stundenplan_Fach> Stundenplan_Fach { get; set; }
    }
}
