//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stundenplan.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Studenplan_Stunden
    {
        public long id { get; set; }
        public long FachId { get; set; }
        public long StundenplanId { get; set; }
        public System.DateTime Begin { get; set; }
        public System.DateTime Ende { get; set; }
        public string Raum { get; set; }
    
        public virtual Stundenplan Stundenplan { get; set; }
        public virtual Stundenplan_Fach Fach { get; set; }
    }
}
