//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stundenplan.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class studenplan_stunden
    {
        public long id { get; set; }
        public long Fach { get; set; }
        public long Stundenplan { get; set; }
        public System.DateTime Begin { get; set; }
        public System.DateTime Ende { get; set; }
        public string Raum { get; set; }
    
        public virtual stundenplan stundenplan { get; set; }
        public virtual stundenplan_fach fach { get; set; }
    }
}
