//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Stundenplan.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Stundenplan_Fach
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stundenplan_Fach()
        {
            this.Stunden = new HashSet<Studenplan_Stunden>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public string Kuerzel { get; set; }
        public Nullable<long> Farbe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Studenplan_Stunden> Stunden { get; set; }
    }
}
